### ISSUE TITLE
Disable bot on short articles

### ISSUE THREAD

**Issue by RealStickman** [RikudouSage/LemmyAutoTldrBot#2]
Today I stumbled upon a post where the summarised article was about as long as the actual article. [Link](https://lemmy.ml/post/3413745)  

The Phoronix article has 139 words or 1021 characters.  
The summary is 135 words / 984 characters.  

I think it would make sense to implement a minimum article length for the bot to create a summary.

**Comment by RikudouSage** [comment]
I think it still serves its purpose of people not having to leave the community to see what the article is about.
