### ISSUE TITLE
Bot triggered twice for the same article

### ISSUE THREAD

**Issue by Christoph-Wagner** [RikudouSage/LemmyAutoTldrBot#3]
[Post](https://lemmy.ml/post/3757291)

* [Comment 1](https://lemmy.ml/comment/2994838)
* [Comment 2](https://lemmy.ml/comment/2994839)

**Comment by Ashvith10** [comment]
Was the cause of the issue detected? If not, might I suggest validating the post for the AutoTL;DR bot first, before posting?
